version: "3.8"

services:
  polybot-dev:
    image: "${IMG_NAME}"
    env_file:
      - .env
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/ubuntu/polybot-dev.crt:/app/polybot-dev.crt
    environment:
      # Make sure your app binds to 0.0.0.0:8443, not just localhost:8443
      - BIND_HOST=0.0.0.0

  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otelcol/config.yaml" ]
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol/config.yaml
      # Mount host filesystem to allow the collector to access host metrics
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
    environment:
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
    network_mode: host