version: "3.8"

services:
  polybot-prod:
    image: "${IMG_NAME}"
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8443:8443"
    volumes:
      - /home/ubuntu/polybot-prod.crt:/app/polybot-prod.crt

  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otelcol/config.yaml" ]
    ports:
      - "8889:8889"  
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol/config.yaml
      # Mount host filesystem to allow the collector to access host metrics
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
    environment:
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
    network_mode: host
